# Regenerates VoiceFlow.App/Resources/Strings.cs from Strings.resx.
# Run it after adding or renaming a key:
#   pwsh tools/generate-strings.ps1

$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$resx = Join-Path $root 'VoiceFlow.App/Resources/Strings.resx'
$target = Join-Path $root 'VoiceFlow.App/Resources/Strings.cs'

[xml]$doc = Get-Content $resx
$keys = $doc.root.data | Where-Object { $_.name } | ForEach-Object { $_.name } | Sort-Object

$builder = [System.Text.StringBuilder]::new()
[void]$builder.AppendLine('// <auto-generated>')
[void]$builder.AppendLine('//     Generated from Strings.resx by tools/generate-strings.ps1. Do not edit by hand.')
[void]$builder.AppendLine('// </auto-generated>')
[void]$builder.AppendLine('#nullable enable')
[void]$builder.AppendLine()
[void]$builder.AppendLine('using System.Globalization;')
[void]$builder.AppendLine('using System.Resources;')
[void]$builder.AppendLine()
[void]$builder.AppendLine('namespace VoiceFlow.App.Resources;')
[void]$builder.AppendLine()
[void]$builder.AppendLine('/// <summary>')
[void]$builder.AppendLine('///   Localised UI strings. Spanish is the neutral culture, English ships as the "en"')
[void]$builder.AppendLine('///   satellite assembly. The culture is chosen once at startup from the settings.')
[void]$builder.AppendLine('/// </summary>')
[void]$builder.AppendLine('public static class Strings')
[void]$builder.AppendLine('{')
[void]$builder.AppendLine('    private static readonly ResourceManager Manager =')
[void]$builder.AppendLine('        new("VoiceFlow.App.Resources.Strings", typeof(Strings).Assembly);')
[void]$builder.AppendLine()
[void]$builder.AppendLine('    /// <summary>Culture used for lookups; null means the neutral (Spanish) resources.</summary>')
[void]$builder.AppendLine('    public static CultureInfo? Culture { get; set; }')
[void]$builder.AppendLine()
[void]$builder.AppendLine('    public static string Get(string key) => Manager.GetString(key, Culture) ?? key;')
[void]$builder.AppendLine()
[void]$builder.AppendLine('    public static string Format(string key, params object?[] args) =>')
[void]$builder.AppendLine('        string.Format(Culture ?? CultureInfo.CurrentCulture, Get(key), args);')

foreach ($key in $keys) {
    [void]$builder.AppendLine()
    [void]$builder.AppendLine("    public static string $key => Get(`"$key`");")
}

[void]$builder.AppendLine('}')

Set-Content -Path $target -Value $builder.ToString() -Encoding UTF8
"Generated $target with $($keys.Count) keys."
