// <auto-generated>
//     Generated from Strings.resx by tools/generate-strings.ps1. Do not edit by hand.
// </auto-generated>
#nullable enable

using System.Globalization;
using System.Resources;

namespace VoiceFlow.App.Resources;

/// <summary>
///   Localised UI strings. Spanish is the neutral culture, English ships as the "en"
///   satellite assembly. The culture is chosen once at startup from the settings.
/// </summary>
public static class Strings
{
    private static readonly ResourceManager Manager =
        new("VoiceFlow.App.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>Culture used for lookups; null means the neutral (Spanish) resources.</summary>
    public static CultureInfo? Culture { get; set; }

    public static string Get(string key) => Manager.GetString(key, Culture) ?? key;

    public static string Format(string key, params object?[] args) =>
        string.Format(Culture ?? CultureInfo.CurrentCulture, Get(key), args);

    public static string Browse => Get("Browse");

    public static string Cancel => Get("Cancel");

    public static string Clear => Get("Clear");

    public static string Close => Get("Close");

    public static string ConnectionOk => Get("ConnectionOk");

    public static string ConnectionOkFormat => Get("ConnectionOkFormat");

    public static string Delete => Get("Delete");

    public static string Duplicate => Get("Duplicate");

    public static string HistoryAllProfiles => Get("HistoryAllProfiles");

    public static string HistoryClearAll => Get("HistoryClearAll");

    public static string HistoryCleared => Get("HistoryCleared");

    public static string HistoryConfirmClear => Get("HistoryConfirmClear");

    public static string HistoryCopyProcessed => Get("HistoryCopyProcessed");

    public static string HistoryCopyRaw => Get("HistoryCopyRaw");

    public static string HistoryCountFormat => Get("HistoryCountFormat");

    public static string HistoryEmpty => Get("HistoryEmpty");

    public static string HistoryEntryDeleted => Get("HistoryEntryDeleted");

    public static string HistoryLlmFailedFormat => Get("HistoryLlmFailedFormat");

    public static string HistoryPasteProblem => Get("HistoryPasteProblem");

    public static string HistoryProcessedCopied => Get("HistoryProcessedCopied");

    public static string HistoryRawCopied => Get("HistoryRawCopied");

    public static string HistoryReadErrorFormat => Get("HistoryReadErrorFormat");

    public static string HistoryReprocess => Get("HistoryReprocess");

    public static string HistoryReprocessedCopied => Get("HistoryReprocessedCopied");

    public static string HistoryReprocessErrorFormat => Get("HistoryReprocessErrorFormat");

    public static string HistoryReprocessingFormat => Get("HistoryReprocessingFormat");

    public static string HistorySearchHint => Get("HistorySearchHint");

    public static string HistoryTitle => Get("HistoryTitle");

    public static string HotkeyInUseFormat => Get("HotkeyInUseFormat");

    public static string HotkeyInvalid => Get("HotkeyInvalid");

    public static string HotkeyRegisterFailedFormat => Get("HotkeyRegisterFailedFormat");

    public static string KeyBackspace => Get("KeyBackspace");

    public static string KeyDelete => Get("KeyDelete");

    public static string KeyDown => Get("KeyDown");

    public static string KeyEnd => Get("KeyEnd");

    public static string KeyEnter => Get("KeyEnter");

    public static string KeyEsc => Get("KeyEsc");

    public static string KeyHome => Get("KeyHome");

    public static string KeyInsert => Get("KeyInsert");

    public static string KeyLeft => Get("KeyLeft");

    public static string KeyPageDown => Get("KeyPageDown");

    public static string KeyPageUp => Get("KeyPageUp");

    public static string KeyRight => Get("KeyRight");

    public static string KeySpace => Get("KeySpace");

    public static string KeyTab => Get("KeyTab");

    public static string KeyUp => Get("KeyUp");

    public static string LanguageEnglish => Get("LanguageEnglish");

    public static string LanguageSpanish => Get("LanguageSpanish");

    public static string MainDictate => Get("MainDictate");

    public static string MainHotkeyLabel => Get("MainHotkeyLabel");

    public static string MainLastDictation => Get("MainLastDictation");

    public static string MainSubtitle => Get("MainSubtitle");

    public static string MessageCopiedNotPasted => Get("MessageCopiedNotPasted");

    public static string MessageDeliveryFailedFormat => Get("MessageDeliveryFailedFormat");

    public static string MessageDictationCancelled => Get("MessageDictationCancelled");

    public static string MessageDictationFailedFormat => Get("MessageDictationFailedFormat");

    public static string MessageHotkeyFailed => Get("MessageHotkeyFailed");

    public static string MessageLlmFallback => Get("MessageLlmFallback");

    public static string MessageMicrophoneFailedFormat => Get("MessageMicrophoneFailedFormat");

    public static string MessageModelMissingTray => Get("MessageModelMissingTray");

    public static string MessageNoTextRecognized => Get("MessageNoTextRecognized");

    public static string MessageRecordingTooShort => Get("MessageRecordingTooShort");

    public static string MessageStartupFailedFormat => Get("MessageStartupFailedFormat");

    public static string MessageUnexpectedError => Get("MessageUnexpectedError");

    public static string ModeHold => Get("ModeHold");

    public static string ModelPickerCountFormat => Get("ModelPickerCountFormat");

    public static string ModelPickerEmpty => Get("ModelPickerEmpty");

    public static string ModelPickerErrorFormat => Get("ModelPickerErrorFormat");

    public static string ModelPickerLoading => Get("ModelPickerLoading");

    public static string ModelPickerOnlyFree => Get("ModelPickerOnlyFree");

    public static string ModelPickerSearchHint => Get("ModelPickerSearchHint");

    public static string ModelPickerTitle => Get("ModelPickerTitle");

    public static string ModelPickerUse => Get("ModelPickerUse");

    public static string ModelStateDownloadedNotLoaded => Get("ModelStateDownloadedNotLoaded");

    public static string ModelStateDownloading => Get("ModelStateDownloading");

    public static string ModelStateFailedFormat => Get("ModelStateFailedFormat");

    public static string ModelStateLoading => Get("ModelStateLoading");

    public static string ModelStateNotDownloaded => Get("ModelStateNotDownloaded");

    public static string ModelStateReady => Get("ModelStateReady");

    public static string ModelStatusChecking => Get("ModelStatusChecking");

    public static string ModelStatusDownloading => Get("ModelStatusDownloading");

    public static string ModelStatusFailedFormat => Get("ModelStatusFailedFormat");

    public static string ModelStatusLoading => Get("ModelStatusLoading");

    public static string ModelStatusMissing => Get("ModelStatusMissing");

    public static string ModelStatusReady => Get("ModelStatusReady");

    public static string ModeToggle => Get("ModeToggle");

    public static string New => Get("New");

    public static string OpenRouterHint => Get("OpenRouterHint");

    public static string ProviderCustom => Get("ProviderCustom");

    public static string Refresh => Get("Refresh");

    public static string Save => Get("Save");

    public static string SettingsApiKey => Get("SettingsApiKey");

    public static string SettingsApiKeyHint => Get("SettingsApiKeyHint");

    public static string SettingsBrowseModels => Get("SettingsBrowseModels");

    public static string SettingsConfirmClearHistory => Get("SettingsConfirmClearHistory");

    public static string SettingsDownloadModel => Get("SettingsDownloadModel");

    public static string SettingsEndpoint => Get("SettingsEndpoint");

    public static string SettingsEndpointExamples => Get("SettingsEndpointExamples");

    public static string SettingsGetApiKey => Get("SettingsGetApiKey");

    public static string SettingsHotkeyCombination => Get("SettingsHotkeyCombination");

    public static string SettingsHotkeyHint => Get("SettingsHotkeyHint");

    public static string SettingsHotkeyHoldOption => Get("SettingsHotkeyHoldOption");

    public static string SettingsHotkeyListening => Get("SettingsHotkeyListening");

    public static string SettingsHotkeyMode => Get("SettingsHotkeyMode");

    public static string SettingsHotkeyNeedsModifier => Get("SettingsHotkeyNeedsModifier");

    public static string SettingsHotkeyRecord => Get("SettingsHotkeyRecord");

    public static string SettingsHotkeyReset => Get("SettingsHotkeyReset");

    public static string SettingsHotkeyToggleOption => Get("SettingsHotkeyToggleOption");

    public static string SettingsInputDevice => Get("SettingsInputDevice");

    public static string SettingsLanguage => Get("SettingsLanguage");

    public static string SettingsLanguageHint => Get("SettingsLanguageHint");

    public static string SettingsMaxAgeDays => Get("SettingsMaxAgeDays");

    public static string SettingsMaxDuration => Get("SettingsMaxDuration");

    public static string SettingsMaxEntries => Get("SettingsMaxEntries");

    public static string SettingsMaxTokens => Get("SettingsMaxTokens");

    public static string SettingsMicTest => Get("SettingsMicTest");

    public static string SettingsMicTestStart => Get("SettingsMicTestStart");

    public static string SettingsMicTestStop => Get("SettingsMicTestStop");

    public static string SettingsMinimizeToTray => Get("SettingsMinimizeToTray");

    public static string SettingsModel => Get("SettingsModel");

    public static string SettingsModelFolder => Get("SettingsModelFolder");

    public static string SettingsModelPickerTitle => Get("SettingsModelPickerTitle");

    public static string SettingsPasteDelay => Get("SettingsPasteDelay");

    public static string SettingsPasteSection => Get("SettingsPasteSection");

    public static string SettingsPlaySounds => Get("SettingsPlaySounds");

    public static string SettingsProfileActiveFormat => Get("SettingsProfileActiveFormat");

    public static string SettingsProfileConfirmDeleteFormat => Get("SettingsProfileConfirmDeleteFormat");

    public static string SettingsProfileModel => Get("SettingsProfileModel");

    public static string SettingsProfileName => Get("SettingsProfileName");

    public static string SettingsProfileNewName => Get("SettingsProfileNewName");

    public static string SettingsProfileNoDefault => Get("SettingsProfileNoDefault");

    public static string SettingsProfilePrompt => Get("SettingsProfilePrompt");

    public static string SettingsProfileRestore => Get("SettingsProfileRestore");

    public static string SettingsProfileRestored => Get("SettingsProfileRestored");

    public static string SettingsProfileSave => Get("SettingsProfileSave");

    public static string SettingsProfileSaved => Get("SettingsProfileSaved");

    public static string SettingsProfileSetActive => Get("SettingsProfileSetActive");

    public static string SettingsProfileTemperature => Get("SettingsProfileTemperature");

    public static string SettingsProfileUsesLlm => Get("SettingsProfileUsesLlm");

    public static string SettingsProvider => Get("SettingsProvider");

    public static string SettingsProviderLabel => Get("SettingsProviderLabel");

    public static string SettingsReasoningEffort => Get("SettingsReasoningEffort");

    public static string SettingsReasoningEnable => Get("SettingsReasoningEnable");

    public static string SettingsReasoningExplanation => Get("SettingsReasoningExplanation");

    public static string SettingsReasoningHigh => Get("SettingsReasoningHigh");

    public static string SettingsReasoningLow => Get("SettingsReasoningLow");

    public static string SettingsReasoningMedium => Get("SettingsReasoningMedium");

    public static string SettingsReasoningTitle => Get("SettingsReasoningTitle");

    public static string SettingsReloadModel => Get("SettingsReloadModel");

    public static string SettingsRestoreClipboard => Get("SettingsRestoreClipboard");

    public static string SettingsRetention => Get("SettingsRetention");

    public static string SettingsRetentionHint => Get("SettingsRetentionHint");

    public static string SettingsSaveAudio => Get("SettingsSaveAudio");

    public static string SettingsStartWithWindows => Get("SettingsStartWithWindows");

    public static string SettingsStatus => Get("SettingsStatus");

    public static string SettingsTemperature => Get("SettingsTemperature");

    public static string SettingsTemperatureBalanced => Get("SettingsTemperatureBalanced");

    public static string SettingsTemperatureCreative => Get("SettingsTemperatureCreative");

    public static string SettingsTemperatureExplanation => Get("SettingsTemperatureExplanation");

    public static string SettingsTemperaturePrecise => Get("SettingsTemperaturePrecise");

    public static string SettingsTestConnection => Get("SettingsTestConnection");

    public static string SettingsTesting => Get("SettingsTesting");

    public static string SettingsThreads => Get("SettingsThreads");

    public static string SettingsTimeout => Get("SettingsTimeout");

    public static string SettingsTitle => Get("SettingsTitle");

    public static string SettingsTokensExplanation => Get("SettingsTokensExplanation");

    public static string SettingsTokensLong => Get("SettingsTokensLong");

    public static string SettingsTokensMax => Get("SettingsTokensMax");

    public static string SettingsTokensShort => Get("SettingsTokensShort");

    public static string SettingsTokensStandard => Get("SettingsTokensStandard");

    public static string SettingsTypeUnicode => Get("SettingsTypeUnicode");

    public static string SetupCancelled => Get("SetupCancelled");

    public static string SetupDownload => Get("SetupDownload");

    public static string SetupHeader => Get("SetupHeader");

    public static string SetupIncompleteFolderFormat => Get("SetupIncompleteFolderFormat");

    public static string SetupLoadingModel => Get("SetupLoadingModel");

    public static string SetupModelLoadFailed => Get("SetupModelLoadFailed");

    public static string SetupModelReady => Get("SetupModelReady");

    public static string SetupPickFolderTitle => Get("SetupPickFolderTitle");

    public static string SetupProgressFormat => Get("SetupProgressFormat");

    public static string SetupSizeFormat => Get("SetupSizeFormat");

    public static string SetupSubtitle => Get("SetupSubtitle");

    public static string SetupTargetFolder => Get("SetupTargetFolder");

    public static string SetupTitle => Get("SetupTitle");

    public static string SetupUseLocalFolder => Get("SetupUseLocalFolder");

    public static string StateError => Get("StateError");

    public static string StateIdle => Get("StateIdle");

    public static string StatePasting => Get("StatePasting");

    public static string StateProcessing => Get("StateProcessing");

    public static string StateRecording => Get("StateRecording");

    public static string StateTranscribing => Get("StateTranscribing");

    public static string TabAi => Get("TabAi");

    public static string TabAudio => Get("TabAudio");

    public static string TabGeneral => Get("TabGeneral");

    public static string TabHistory => Get("TabHistory");

    public static string TabHotkey => Get("TabHotkey");

    public static string TabProfiles => Get("TabProfiles");

    public static string TabTranscription => Get("TabTranscription");

    public static string TrayActiveProfile => Get("TrayActiveProfile");

    public static string TrayExit => Get("TrayExit");

    public static string TrayHistory => Get("TrayHistory");

    public static string TrayOpen => Get("TrayOpen");

    public static string TraySettings => Get("TraySettings");

    public static string UnknownError => Get("UnknownError");
}

